#!/usr/bin/env groovy

/**
 * Copyright (C) Couchbase, Inc 2020 - All Rights Reserved
 * Unauthorized copying of this file, via any medium is strictly prohibited
 * Proprietary and confidential.
 *
 * When updating this Jenkinsfile, changes will not take effect immediately; they will take effect once the Jenkins
 * multi-branch pipeline picks up the commit. This therefore means that changes made to the Jenkinsfile in a Gerrit
 * review will not have any effect until they are submitted.
 */

import hudson.model.Result
import hudson.model.Run
import jenkins.model.CauseOfInterruption.UserInterruption

pipeline {
    agent { label "linux&&master&&large&&!aarch64" }

    environment {
        SOURCE = "${WORKSPACE}/source"
        EXAMINADOR = "${WORKSPACE}/examinador"

        GO_TARBALL_URL = "https://go.dev/dl/go1.25.3.linux-amd64.tar.gz"
    }

    stages {
        stage("Setup") {
            steps {
                script {
                    // Configure Gerrit Trigger
                    properties([pipelineTriggers([
                        gerrit(
                            serverName: "review.couchbase.org",
                            gerritProjects: [
                                [
                                    compareType: "PLAIN", disableStrictForbiddenFileVerification: false, pattern: "examinador",
                                    branches: [[ compareType: "PLAIN", pattern: "master" ]]
                                ],
                            ],
                            triggerOnEvents: [
                                commentAddedContains(commentAddedCommentContains: "reverify"),
                                draftPublished(),
                                patchsetCreated(excludeNoCodeChange: true)
                            ]
                        )
                    ])])
                }
            }
        }

        stage("Setup Examinador") {
            environment {
                GOROOT = "${WORKSPACE}/go"
                GOBIN = "${GOROOT}/bin"
                PATH="${PATH}:${GOBIN}"
            }

            steps {
                dir("${WORKSPACE}") {
                    sh "wget -q -O- ${GO_TARBALL_URL} | tar xz"
                    sh "go version"
                    sh "go install github.com/minio/minio@latest"
                    sh "minio --version"
                    sh "git clone git@github.com:couchbaselabs/examinador.git"
                }

                dir("${EXAMINADOR}") {
                    // Use python virtual environment to make life easier
                    sh '''#!/bin/bash
                        git fetch ssh://buildbot@review.couchbase.org:29418/examinador ${GERRIT_REFSPEC}
                        git checkout FETCH_HEAD
                        python3 -m venv robot-env
                        source robot-env/bin/activate
                        pip3 install urllib3 pylint requests mypy
                        pip3 install wheel
                        pip3 install cmake scikit-build==0.15.0
                        pip3 install couchbase==3.2.7 --no-build-isolation
                        pip3 install -r requirements.txt
                    '''
                }
            }
        }

        stage("Lint") {
            steps {
                timeout(time: 10, unit: "MINUTES") {
                    dir("${EXAMINADOR}") {
                        sh '''#!/bin/bash
                              source robot-env/bin/activate
                              python3 -m pylint --rcfile=${EXAMINADOR}/.pylintrc libraries
                        '''
                    }
                }
            }
        }

        stage("Type check") {
            steps {
                timeout(time: 10, unit: "MINUTES") {
                    dir("${EXAMINADOR}") {
                        sh """#!/bin/bash
                            source robot-env/bin/activate
                            if [ \$(mypy --ignore-missing-imports libraries | grep -c error) -gt 1 ]; then
                                echo "Failed mypy type checking in libraries"
                                echo "Re running: mypy --ignore-missing-imports libraries"
                                echo \$(mypy --ignore-missing-imports libraries)
                                exit 1
                            fi
                           """
                    }
                }
            }
        }

        stage("Get CB") {
            steps {
                timeout(time: 25, unit: "MINUTES") {
                    dir("${SOURCE}") {
                        sh "repo init -u https://github.com/couchbase/manifest -m branch-master.xml -g all"
                        sh "repo sync -j8"
                    }
                }
            }
        }

        stage("Build CB") {
            steps {
                timeout(time: 60, unit: "MINUTES") {
                    dir("${SOURCE}") {
                        sh "make -j8"
                    }
                }
            }
        }

        stage("Test") {
            environment {
                GOROOT = "${WORKSPACE}/go"
                GOBIN = "${GOROOT}/bin"
                PATH="${PATH}:${GOBIN}"
            }

            steps{
                dir("${EXAMINADOR}") {
                    sh '''#!/bin/bash
                          source robot-env/bin/activate
                          robot-env/bin/robot --variable SOURCE:${SOURCE} --variable WORKSPACE:${WORKSPACE} --variable DELETE_LOGS:True --outputdir ${WORKSPACE}/reports --exclude in_progress --exclude UI --exclude wait_for_bug_fix --consolewidth 120 -L DEBUG cbm_tests cbm_cloud_integration_tests rest_api_tests rest_api_longer
                    '''
                }
            }
        }

    }

    post {
        always {
            // Post the test results
            script {
              step(
                    [
                      $class              : 'RobotPublisher',
                      outputPath          : 'reports',
                      outputFileName      : 'output.xml',
                      reportFileName      : 'report.html',
                      logFileName         : 'log.html',
                      otherFiles          : '*.zip',
                      disableArchiveOutput: false,
                      passThreshold       : 100,
                      unstableThreshold   : 95,
                    ]
                )
            }
        }

        cleanup {
            // Remove the workspace
            deleteDir()
        }
    }
}
